name: Deploy PROD

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Deploy PROD
        run: |
          cd /opt/taskflow
          git pull origin main
          bash deploy-prod.sh
