name: Deploy QAS

on:
  push:
    branches: [staging]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Deploy QAS
        run: |
          git config --global --add safe.directory /opt/taskflow-qas
          cd /opt/taskflow-qas
          git pull origin staging
          bash deploy-qas.sh
