name: Deploy PROD

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Deploy PROD
        run: |
          git config --global --add safe.directory /opt/taskflow
          cd /opt/taskflow
          git pull origin main
          bash deploy-prod.sh
